# Generated by Django 5.2.15 on 2026-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_truckingcompany_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckavailability',
            name='destination_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='truckavailability',
            name='destination_state',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
