# Generated by Django 5.2.15 on 2026-06-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_truck_destination_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckavailability',
            name='lane',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='truckavailability',
            name='port_of_entry',
            field=models.CharField(blank=True, choices=[('LAREDO', 'Laredo'), ('EL_PASO', 'El Paso'), ('TIJUANA', 'Tijuana')], max_length=20),
        ),
        migrations.AddField(
            model_name='truckavailability',
            name='potential_lane',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='truckavailability',
            name='spot_lane',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='truckavailability',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
